name = "markdown-converter"
main = "src/index.js"
compatibility_date = "2023-10-30"

[ai]
binding = "AI"

[vars]
APP_PASSWORD = "admin123"  # 默认密码，生产环境请修改为更复杂的密码

# 支持的语言配置
# 应用默认支持多语言（英文、中文、日语）
# 通过URL参数访问不同语言版本：
# - 英文: ?lang=en
# - 中文: ?lang=zh (默认)
# - 日语: ?lang=jp
